import { clsx } from "clsx";

import type { Metadata } from "next";
import { fonts } from "@/lib/site/fonts";

import "@/styles/index.css";
import { Providers } from "@/components/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={clsx(fonts)}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
